services:
  backend:
    build:
      context: ./repeateat-backend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./repeateat-backend/:/usr/src/app
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:secretpassword@postgres:5432/repeateat_db
    container_name: repeateat-backend-dev
  frontend:
    build:
      context: ./repeateat-frontend
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./repeateat-frontend/:/usr/src/app
      - /usr/src/app/node_modules
    container_name: repeateat-frontend-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
  postgres:
    image: postgres:18
    container_name: repeateat-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: repeateat_db
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - 5434:5432
    volumes:
      - repeateat_pgdata:/var/lib/postgresql
    restart: unless-stopped

volumes:
  repeateat_pgdata:
