services:
  backend:
    build:
      context: ./repeateat-backend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./repeateat-backend/:/usr/src/app
    environment:
      - PORT=3000
    container_name: repeateat-backend-dev
  frontend:
    build:
      context: ./repeateat-frontend
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./repeateat-frontend/:/usr/src/app
    container_name: repeateat-frontend-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
